### ISSUE TITLE
where is python_pydiction.vim ???

### ISSUE THREAD

**Issue by leoli2012** [rkulla/pydiction#6]
Where is python_pydiction.vim??there are nothing this file......

**Comment by rkulla** [comment]
It's in the after/ftplugin directory where it belongs. See https://github.com/rkulla/pydiction/blob/master/after/ftplugin/python_pydiction.vim

**Comment by rkulla** [comment]
I just updated the README to specify that more explicitly. Thanks for pointing that out.

**Comment by leoli2012** [comment]
thanks for you help~~i will try
